#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-backgrounds
Version  : 41.0
Release  : 19
URL      : https://download.gnome.org/sources/gnome-backgrounds/41/gnome-backgrounds-41.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-backgrounds/41/gnome-backgrounds-41.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-2.0 CC-BY-SA-2.0 CC-BY-SA-3.0 GPL-2.0
Requires: gnome-backgrounds-data = %{version}-%{release}
Requires: gnome-backgrounds-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gettext
BuildRequires : itstool

%description
# GNOME Backgrounds
This module contains a set of backgrounds packaged with the GNOME desktop.

%package data
Summary: data components for the gnome-backgrounds package.
Group: Data

%description data
data components for the gnome-backgrounds package.


%package license
Summary: license components for the gnome-backgrounds package.
Group: Default

%description license
license components for the gnome-backgrounds package.


%prep
%setup -q -n gnome-backgrounds-41.0
cd %{_builddir}/gnome-backgrounds-41.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632494156
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-backgrounds
cp %{_builddir}/gnome-backgrounds-41.0/COPYING %{buildroot}/usr/share/package-licenses/gnome-backgrounds/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
cp %{_builddir}/gnome-backgrounds-41.0/COPYING_CCBY2 %{buildroot}/usr/share/package-licenses/gnome-backgrounds/48ae520e2eac2703fc9163f96f183305e888e26b
cp %{_builddir}/gnome-backgrounds-41.0/COPYING_CCBYSA2 %{buildroot}/usr/share/package-licenses/gnome-backgrounds/567ee727cac3676fee95a4529f868aad987b68c9
cp %{_builddir}/gnome-backgrounds-41.0/COPYING_CCBYSA3 %{buildroot}/usr/share/package-licenses/gnome-backgrounds/2995e7d53219d710383087253fb9a1e760e44f35
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/backgrounds/gnome/Blobs.svg
/usr/share/backgrounds/gnome/BrushStrokes.jpg
/usr/share/backgrounds/gnome/ColdWarm.jpg
/usr/share/backgrounds/gnome/Disco.jpg
/usr/share/backgrounds/gnome/DiscoHex.jpg
/usr/share/backgrounds/gnome/Frosty.jpg
/usr/share/backgrounds/gnome/Leaf.jpg
/usr/share/backgrounds/gnome/LightBulb.jpg
/usr/share/backgrounds/gnome/Loveles.jpg
/usr/share/backgrounds/gnome/Symbolics-1.png
/usr/share/backgrounds/gnome/VNC.png
/usr/share/backgrounds/gnome/Wood.jpg
/usr/share/backgrounds/gnome/adwaita-day.png
/usr/share/backgrounds/gnome/adwaita-morning.png
/usr/share/backgrounds/gnome/adwaita-night.png
/usr/share/backgrounds/gnome/adwaita-timed.xml
/usr/share/gnome-background-properties/adwaita.xml
/usr/share/gnome-background-properties/gnome-backgrounds.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-backgrounds/13d2034b5ee3cb8d1a076370cf8f0e344a5d0855
/usr/share/package-licenses/gnome-backgrounds/2995e7d53219d710383087253fb9a1e760e44f35
/usr/share/package-licenses/gnome-backgrounds/48ae520e2eac2703fc9163f96f183305e888e26b
/usr/share/package-licenses/gnome-backgrounds/567ee727cac3676fee95a4529f868aad987b68c9
